"""initial

Revision ID: 5c77effa862e
Revises:
Create Date: 2024-05-20 15:10:42.156749

"""

# revision identifiers, used by Alembic.
revision = "5c77effa862e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
