"""todoelem_init

Revision ID: 64cabf244a7c
Revises: 5c77effa862e
Create Date: 2024-08-06 00:23:22.467935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cabf244a7c'
down_revision = '5c77effa862e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'todoelem',
        sa.Column('id', sa.Integer(), nullable=False, comment='id primary key'),
        sa.Column('name', sa.String(length=200), nullable=True, comment='name'),
        sa.Column('description', sa.String(length=2000), nullable=True, comment='description'),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=True,
        ),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todoelem')
    # ### end Alembic commands ###
