name: Sync To Gitee
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/wu-wenxiang/fastapi-todo-list-demo.git"
          destination-repo: "git@gitee.com:wu-wen-xiang/fastapi-todo-list-demo.git"
